### ISSUE TITLE
Process queue at specified time

### ISSUE THREAD

**Issue by alejomendoza** [firebase/firebase-queue#102]
It would be great if we can process tasks at a certain time, so the queue won't execute right away but on a specified timestamp. A similar solution would be the `fire-task-queue` but it is using an outdated version of firebase. This would be useful to schedule tasks that we don't want to execute immediately like refreshing a signed asset url before it expires. I sent you an email @drtriumph, thanks for this amazing repo!

**Comment by katowulf** [comment]
Dup of #35. See also #79 and #89. Thanks for adding your vote!
