### ISSUE TITLE
Question - Is it safe to use cluster, a.k.a parallelism, with Firebase queue

### ISSUE THREAD

**Issue by ivawzh** [firebase/firebase-queue#108]
From the doc, we learned that you can run multiple workers on the same thread in one CPU core. Will there be any reason stopping us from running Firebase Queue in NodeJs cluster, that is, multiple threads with multiple CPU cores; or running multiple Firebase Queues across multiple EC2 instances?

Thanks.

**Comment by ORESoftware** [comment]
As a user, my guess is that it's totally safe.  As usual, the database handles locking, atomicity, etc. Firebase-queue is essentially parallel whether it's running in a single process, or multiple processes.

**Comment by ivawzh** [comment]
@ORESoftware I have the same assumption. Just want to get confirmation or future-proof guarantee from Firebase team in case breaking anything in production.

**Comment by IljaDaderko** [comment]
Would be nice to see confirmation on this as well +1

**Comment by drtriumph** [comment]
I have not used cluster with this library before - I see no reason it shouldn't work but I can't make any guarantees.
