### ISSUE TITLE
retries do not work for me

### ISSUE THREAD

**Issue by slootzky** [firebase/firebase-queue#110]
just posted it as a question in Stackoverflow

[http://stackoverflow.com/questions/42231385/firebase-queue-retries-are-not-working](SO)

I'm using the latest for all libs (firebase & firebase-queue) and node 6.9.1

**Comment by Caerbannog** [comment]
You are making the mistake outline in point 1 of this comment: https://github.com/firebase/firebase-queue/issues/106#issuecomment-279975546
Your "default_spec" will not be used.
