### ISSUE TITLE
What happens if the worker dies while processing?

### ISSUE THREAD

**Issue by seanhess** [firebase/firebase-queue#17]
If I run the test from the readme, and kill the node process between when it accepts the job and when it resolves it, it just sits in the tasks queue forever. 

Is this acceptable behavior for a messaging system? It will collect garbage over time. I would expect a robust system to detect that the old job has expired and move it to an error state or something.

**Comment by seanhess** [comment]
Ah, I misread the timeout... I thought it was 30s, but it is actually 5 minutes. It does clean up successfully in this case. Good work guys!

**Comment by drtriumph** [comment]
Glad you got it working, this isn't the first time this has caused issues - I'll take a look at making it more clear in the readme
