### ISSUE TITLE
Possible to grab the taskId generated by Firebase?

### ISSUE THREAD

**Issue by henry74** [firebase/firebase-queue#29]
I'd like to leverage the unique id created by Firebase when pushing a task on the queue.  Is it possible to extract this from the data from the worker side or does it need to be explicitly added to the data payload?

**Comment by drtriumph** [comment]
The client that added it generates the ID, so you can always put that info in the task itself.

Assuming you're using the JavaScript SDK (the others are only syntactically different), instead of calling
```js
tasksRef.push({
  your: 'task'
});
```
You could:
```js
var task = tasksRef.push(); // A client-only command
task.set({
  your: 'task',
  id: task.key();
});
```
