### ISSUE TITLE
Tasks left unprocessed when indexOn: ["_state"] enabled

### ISSUE THREAD

**Issue by dreadjr** [firebase/firebase-queue#31]
I am having an issue when i have IndexOn: ["_state"] and tasks are being left unprocessed until the process is restarted.

I created a simple reproducible [repo][1] with the code and package versions. Maybe i am doing something stupid, please let me know if you can reproduce or what is wrong.

[1]: https://github.com/dreadjr/firebase-queue-indexOn

**Comment by drtriumph** [comment]
Looking into this - likely a Firebase client bug

**Comment by dreadjr** [comment]
Makes sense. I'll see if I can narrow it down to a query from the client.

**Comment by jdimond** [comment]
@dreadjr we tracked the issue down to a quirk in the way we raise events for indexed data in the firebase client and the way firebase-queue responds to events. I think we have enough info now to work on a fix.

**Comment by dreadjr** [comment]
Sweet. Thanks.

**Comment by dreadjr** [comment]
Any progress on this issue?

**Comment by albertolobrano** [comment]
what is the status on this ?

**Comment by jdimond** [comment]
@dreadjr this should have been fixed with version 2.3.0 of the client library. Closing, please reopen if you think this is still broken.
