### ISSUE TITLE
How can I send a response to my client that the submitted task has been Completed by the worker?

### ISSUE THREAD

**Issue by sivaramsi** [firebase/firebase-queue#33]
In my client Will I have to watch the task for any changes in states or any other way to do this.

**Comment by drtriumph** [comment]
Watching the state (or deletion) of the task that the client pushed onto the queue is a great way to monitor progress from the client.

You could update some other location in your Firebase database that both the client and the queue worker know about, but that gets complicated quickly and is unnecessary. There's currently no way to push data to a client that's not listening on a Firebase reference.
