### ISSUE TITLE
Restarting a firebase-queue with existing tasks in the tasks array causes problems.

### ISSUE THREAD

**Issue by richtera** [firebase/firebase-queue#44]
It seems that I am unable to get it to execute all of the tasks if the queue was shutdown for a period and tasks were piled up into the tasks array. It executed 2 times the number of numWorkers and then waits for new tasks to come in. Am I doing something wrong or is that how firebase queues work?
Thanks for any information.

**Comment by tsemerad** [comment]
I had the same issue. It appears a temporary fix is to remove the `".indexOn": "_state"` from your security rules. It looks like the Firebase team is working on resolving the issue. See issue #43.

**Comment by drtriumph** [comment]
The underlying issue was fixed in an update to the database last Friday. Please reopen if you're still seeing issues
