### ISSUE TITLE
Possible bug in QueueWorker.prototype._reject

### ISSUE THREAD

**Issue by meticoeus** [firebase/firebase-queue#56]
QueueWorker.prototype._reject creates a function that takes a parameter "error".
The transaction complete handler masks "error" with its own "error" which is passed to the recursive attempt upon failure.

I would expect the behavior to keep trying to log the original error instead of the failed transaction attempt.

Is this intended or just a bug?

**Comment by drtriumph** [comment]
nope, that's a bug. I'll upgrade the repo to use eslint which would have caught this, thanks for pointing it out
