### ISSUE TITLE
Firebase 3.x support?

### ISSUE THREAD

**Issue by chrismbeckett** [firebase/firebase-queue#64]
I didn't see anything in the recent announcements concerns Firebase Queues? Is this going to continue to be supported?

**Comment by katowulf** [comment]
> I didn't see anything in the recent announcements concerns Firebase Queues?
This is a bit low level to be announced at I/O. That's no indication that it's been forgotten. Support for the new SDK versions will certainly be implemented at some time. PRs welcome.

**Comment by chrismbeckett** [comment]
I guess I was mistaken in thinking this was an actual supported feature of Firebase? So anyone currently using queues in their app can't upgrade until *some time*? Anyway, thx for the response. If this isn't a supported feature I don't think I can use it.

**Comment by steida** [comment]
@katowulf I would suggest opening a new issue where people can discuss refactoring and track progress.

**Comment by drtriumph** [comment]
Apologies for the delay - been a crazy few days around here. #66 should address your concerns

**Comment by chrismbeckett** [comment]
Thanks for the update Chris. Definitely excited by Firebase 3x. Looks like it may be time to migrate from Heroku to Google App Engine Flex now that it supports Node.js. Support for files and a more complete auth system are very welcome updates.
