### ISSUE TITLE
Process never terminates.

### ISSUE THREAD

**Issue by adjohnson916** [firebase/firebase-queue#70]
### Version info

**Firebase:** 2.4.2

**Firebase Queue:** 1.3.1

**Node.js:** 5.11.0

**Other (e.g. operating system) (if applicable):** OS X 10.11.5

### Test case

```js
var Firebase, Queue, queue;
Firebase = require('firebase');
Queue = require('firebase-queue');
queue = new Queue(new Firebase('https://fir-queue-forever.firebaseio.com'), function() {});
queue.shutdown().then(function() {
  return console.log('shut down');
});
```

### Steps to reproduce

Run script above from a file with node on the command line.

### Expected behavior

The process should terminate after shutdown.

### Actual behavior

The process hangs forever.

**Comment by drtriumph** [comment]
This is a limitation of the way the current Firebase client handles the persistent connection and not an issue with the queue itself. The [documentation](https://github.com/firebase/firebase-queue/blob/master/docs/guide.md#graceful-shutdown) suggests the workaround of a `process.exit(0)` in the `.then()`. A smaller repro would be:

```js
var Firebase = require('firebase');
var ref = new Firebase('https://fir-queue-forever.firebaseio.com');
console.log('Process hangs forever...');
```

**Comment by adjohnson916** [comment]
@drtriumph Ah, thanks. That's unfortunate. How do you get your processes to close for your unit tests? I'm using tape not mocha, maybe that's my issue.
