### ISSUE TITLE
Task was malformed error

### ISSUE THREAD

**Issue by kanishkatn** [firebase/firebase-queue#80]
Hi,

I am getting this error in the queue worker

> FIREBASE WARNING: Using an unspecified index. Consider adding ".indexOn": "_state" at /queue/tasks to your security rules for better performance 
> FIREBASE WARNING: Using an unspecified index. Consider adding ".indexOn": "_state" at /queue/tasks to your security rules for better performance 

I am following the guide. Not sure what I have done wrong.

This is the snapshot of 
![screen shot 2016-09-28 at 3 12 13 pm](https://cloud.githubusercontent.com/assets/4919645/18908645/0e9eff2a-858e-11e6-9cdb-b9423d92a247.png)
the queue

UPDATE: I got past the permission warning, but still the task is malforming. 

Here is the stack trace 

> "Error: Task was malformed\n    at Object.update (/Users/kanishkanagaraj/JeetLab/BetMe/firebase-queue/node_modules/firebase-queue/dist/lib/queue_worker.js:446:27)\n    at ei (/Users/kanishkanagaraj/JeetLab/BetMe/firebase-queue/node_modules/firebase/database-node.js:217:395)\n    at U.h.transaction (/Users/kanishkanagaraj/JeetLab/BetMe/firebase-queue/node_modules/firebase/database-node.js:232:466)\n    at /Users/kanishkanagaraj/JeetLab/BetMe/firebase-queue/node_modules/firebase-queue/dist/lib/queue_worker.js:439:30\n    at c (/Users/kanishkanagaraj/JeetLab/BetMe/firebase-queue/node_modules/firebase/database-node.js:153:58)\n    at /Users/kanishkanagaraj/JeetLab/BetMe/firebase-queue/node_modules/firebase/database-node.js:144:614\n    at Qb (/Users/kanishkanagaraj/JeetLab/BetMe/firebase-queue/node_modules/firebase/database-node.js:43:165)\n    at sc (/Users/kanishkanagaraj/JeetLab/BetMe/firebase-queue/node_modules/firebase/database-node.js:31:216)\n    at rc (/Users/kanishkanagaraj/JeetLab/BetMe/firebase-queue/node_modules/firebase/database-node.js:30:1104)\n    at yg (/Users/kanishkanagaraj/JeetLab/BetMe/firebase-queue/node_modules/firebase/database-node.js:215:313)"

### Version info

**Firebase:** 3

**Firebase Queue:** latest

**Node.js:** latest

**Other (e.g. operating system) (if applicable):** mac os x

**Comment by drtriumph** [comment]
Looks like you're trying to add a task that's just a string - you need to add an object to the queue, so your payload is a sub-key of that task
