### ISSUE TITLE
Semantics issue

### ISSUE THREAD

**Issue by ORESoftware** [firebase/firebase-queue#81]
Looks like creating a `new Queue` does not create separate processes for each worker, it's all still a regular single process node.js process. So you can have set your Queue to have 100 workers, but it's all in a single node.js process.

But in the docs it says:

> The basic unit of the queue is the queue worker: the process that claims a task, performs the appropriate processing on the data, and either returns the transformed data, or an appropriate error.

This doesn't really explain how a worker really works in this library. My only guess is that the number of workers dictates the maximum amount of work that can happen concurrently? My beef is that using the word "process" suggests separate node.js processes, but that's not the case? Or is it?

**Comment by drtriumph** [comment]
That's not the case - we don't do any child process spawning. Multiple processes requires instantiating multiple Queues in separate processes - the choice of how to implement that is left to the user

I'll change the word 'process' (meaning sequence of steps in this case), I can see how there may be some confusion.
