### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by RdeWilde** [firebase/firebase-queue#86]
Is this repository still maintained? As last issue responses and commits are from months ago. Any status update?

**Comment by jwngr** [comment]
Firebase Queue is not deserted and we actually use it in production here at Firebase. We just haven't had any features or bugs lately that we though warranted new code. Also, the primary author (@drtriumph) has been heads down working on some other projects. Apologies for not getting answers to open issues lately. I'll see if we can get some movement on the open issues in the coming days.
