### ISSUE TITLE
Firebase queue not processing any tasks pushed from Android client

### ISSUE THREAD

**Issue by arniesaha** [firebase/firebase-queue#98]
Hello Guys,

We have a node server processing firebase queue, whose instance is running on AWS. These were working as expecting until a few days back with no changes on our server, and now it seems to have stopped working altogether. 

The queue functioned as expected with the below server snippet: db screenshot: 
![firedb](https://cloud.githubusercontent.com/assets/3646287/21340638/e3a60ec4-c6ad-11e6-97fc-0d3e55d0dc87.jpg) 
 
var Queue = require('firebase-queue');
var firebase = require('firebase');
 
firebase.initializeApp({
  serviceAccount: "path/to/serviceAccountCredentials.json'",
  databaseURL: "https://<our-db-id>.firebaseio.com/"
});
 
var ref = firebase.database().ref('queue');
var queue = new Queue(ref, function (data, progress, resolve, reject) {
    processData(data);
   console.log(data);
    setTimeout(function () {
        resolve();
    }, 1000)
});
 
But, after the queue stopped working, saw some changes in the library itself and documentation described use of “firebase-admin” on the server side.
As per this: https://github.com/firebase/firebase-queue/blob/master/docs/guide.md
 
 
Updated the following versions on our Node Server (Node version: v5.6.0):
"firebase": "^3.6.4",
"firebase-admin": "^4.0.4",
"firebase-queue": "^1.6.0"
 
And updated server code is:
 
var Queue = require("firebase-queue");
var admin = require("firebase-admin");
 
var serviceAccount = require('path/to/serviceAccountCredentials.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: '<your-database-url>'
});
 
var ref = admin.database().ref('queue');
var queue = new Queue(ref, function (data, progress, resolve, reject) {
    processData(data);
    console.log(data);
    setTimeout(function () {
        resolve();
    }, 1000)
 
});
 
Android Gradle imports:
compile 'com.google.firebase:firebase-database:9.2.0'
compile 'com.google.firebase:firebase-auth:9.2.0'
 
And e.g. client side firebase push method is:
 
private void savetoFirebaseQueue(String type) {
        DatabaseReference ref = FirebaseDatabase.getInstance()
                .getReferenceFromUrl(Constants.FIREBASE_URL + "queue/tasks");
        Map<String, String> task = new HashMap<>();
        task.put("type_task", type);
        task.put("reciever_id", OhaiApplication.pushyId);
        task.put("sender_id", OhaiApplication.cCSharedPreferences.getPrefVal("pushyId"));
        ref.push().setValue(task);
    }
 
Related entry in tasks/queue is:
KZ6mGJYJUYGb3o2V0rO
mac: "66:cc:2e:xx:xx:xx"
pushtime: "1481894336083"
reciever_id: "fxxxxxxxxxxxxxxx"
sender_id: "0xxxxxxxxxxx"
type_task: "syncProfiles"
userid: "97xxxxxxxx"
 
These entries are not processed anymore. Some similar behaviour with non-processing of the queue is on github too: https://github.com/firebase/firebase-queue/issues/67
 
And they seem to get fixed by itself and reoccur erratically? Need to understand if firebase-queue is a reliable choice for production use?

Any help is much appreciated.

Regards,
Arnab

**Comment by drtriumph** [comment]
Forgive me if this is not the case, but it looks like you have enough data in your realtime database for the console to now be in non-realtime mode. If your data has been growing steadily, you might have just passed the limit that switches. Have you verified that the tasks are not being processed on the server? You can either try refreshing the console to get an updated view of the database, or navigating to a deeper path in your database with less data to get back to realtime mode in the console

**Comment by arniesaha** [comment]
Yes, ofcourse have checked on the server. It doesn't process and have
drilled down to realtime view on the dashboard too. The server doesn't give
any error for the queue neither does it process it.

Have provided all snippets in earlier email. Looking for a better answer or
resolution on this

Arnab


On Dec 22, 2016 5:01 AM, "Chris Raynor" <notifications@github.com> wrote:

Forgive me if this is not the case, but it looks like you have enough data
in your realtime database for the console to now be in non-realtime mode.
If your data has been growing steadily, you might have just passed the
limit that switches. Have you verified that the tasks are not being
processed on the server? You can either try refreshing the console to get
an updated view of the database, or navigating to a deeper path in your
database with less data to get back to realtime mode in the console

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/firebase/firebase-queue/issues/98#issuecomment-268673218>,
or mute the thread

**Comment by arniesaha** [comment]
While, the Firebase rules were correct and as expected. The issue was not reproducible locally and executed the queue when ran locally. Restarted the aws instance, and the queue started working again as expected.

Strange though, since I still don’t exactly know the reason why it had stopped working. But nevertheless, things look fine again.

Closing this. Thanks
